return {
  -- { "EdenEast/nightfox.nvim" },
  -- {
  --   "maxmx03/solarized.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   ---@type solarized.config
  --   opts = {},
  --   config = function(_, opts)
  --     vim.o.termguicolors = true
  --     vim.o.background = "light"
  --     require("solarized").setup(opts)
  --   end,
  -- },
  -- {
  --   "nyoom-engineering/oxocarbon.nvim",
  --   -- Add in any other configuration;
  --   --   event = foo,
  --   --   config = bar
  --   --   end,
  -- },
  -- {
  --   "scottmckendry/cyberdream.nvim",
  --   lazy = false,
  --   priority = 1000,
  -- },
  -- { "bluz71/vim-moonfly-colors", name = "moonfly", lazy = false, priority = 1000 },
  -- {
  --   "navarasu/onedark.nvim",
  --   version = "v0.1.0", -- Pin to legacy version
  --   priority = 1000,
  --   config = function()
  --     require("onedark").setup({
  --       style = "dark",
  --     })
  --     require("onedark").load()
  --   end,
  -- },
  -- {
  --   "rebelot/kanagawa.nvim",
  --   name = "kanagawa",
  --   priority = 1000,
  --   lazy = false,
  --   config = {
  --     -- theme = "wave", -- Load "wave" theme
  --     background = { -- map the value of 'background' option to a theme
  --       dark = "dragon", -- try "dragon" !
  --       light = "lotus",
  --     },
  --   },
  -- },
  -- {
  --   "olimorris/onedarkpro.nvim",
  --   priority = 1000, -- Ensure it loads first
  -- },
  --
  -- {
  --   "LazyVim/LazyVim",
  --   opts = {
  --     colorscheme = "onedark",
  --   },
  -- },

  -- {
  --   "folke/tokyonight.nvim",
  --   opts = {
  --     transparent = true,
  --     styles = {
  --       sidebars = "transparent",
  --       floats = "transparent",
  --     },
  --   },
  -- },
  -- {
  --   "scottmckendry/cyberdream.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   -- options = {
  --   --   transparent = true,
  --   -- },
  --   config = function()
  --     require("cyberdream").setup({
  --       transparent = true,
  --     })
  --   end,
  -- },
  -- {
  --   "LazyVim/LazyVim",
  --   opts = {
  --     colorscheme = "cyberdream",
  --   },
  -- },
}
